development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  
test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: quake_sphere_production
